export { default as Cart } from './Cart/Cart.jsx'
export { default as Register } from './Register/Register.jsx'
export { default as Home } from './Home/Home.jsx'
export { default as Login } from './Login/Login.jsx'
export { default as Admin } from './Admin/Admin.jsx'
export { default as MyRes } from './MyRes/MyRes.jsx'
